-- Add is_bonus and next_day_idea columns to blocs table
ALTER TABLE blocs
ADD COLUMN IF NOT EXISTS is_bonus BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS next_day_idea TEXT;

-- Add comment
COMMENT ON COLUMN blocs.is_bonus IS 'Flag to indicate if the bloc is a bonus bloc (not part of the daily schedule)';
COMMENT ON COLUMN blocs.next_day_idea IS 'Teaser for the next day''s topic generated by AI';
